name: Development
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu]
        ruby: [2.5, 2.6, 2.7]
        experimental: [false]
        include:
        - ruby: ruby-head
          experimental: true
        - ruby: ruby-debug
          experimental: true

    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - run: bundle install
    - run: bundle exec rake
